# Generated by Django 5.1.6 on 2025-02-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carlist_description_carlist_image_carlist_rent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarList',
            new_name='Car',
        ),
    ]
