# Generated by Django 5.1.6 on 2025-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='drop_off_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='pick_up_time',
            field=models.TimeField(),
        ),
    ]
