# Generated by Django 5.1.6 on 2025-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carbooking_drop_off_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='pick_up_location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='drop_off_location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
    ]
