# Generated by Django 5.1.6 on 2025-03-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carbooking_pick_up_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarBooking',
        ),
    ]
