# Generated by Django 5.1.6 on 2025-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('review', models.TextField(default='CarBook makes car rentals super easy with a smooth booking process and great user experience!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
