# Generated by Django 5.1.6 on 2025-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_payment_carbooking_deposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='booking_id',
            field=models.CharField(default=123, max_length=30),
        ),
    ]
